import "./globals.css";
import { Inter } from "next/font/google";
import { ServerThemeProvider } from "@wits/next-themes";
import { siteMetadata } from "./data/siteMetaData";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <ServerThemeProvider attribute="class" defaultTheme={siteMetadata.theme}>
      <html lang="en" className="text-black dark:text-white">
        <body className={inter.className}>{children}</body>
      </html>
    </ServerThemeProvider>
  );
}
